import {
  Bike,
  Car,
  CookingPot,
  Droplets,
  FileText,
  Hand,
  HelpCircle,
  KeyRound,
  LogIn,
  LogOut,
  MapPin,
  Moon,
  ParkingCircle,
  Pill,
  ScrollText,
  ShieldAlert,
  ShoppingCart,
  Sparkles,
  Stethoscope,
  Thermometer,
  TrainFront,
  Trash2,
  Tv,
  Utensils,
  UtensilsCrossed,
  WashingMachine,
  Wifi,
  type LucideIcon,
} from "lucide-react";

/** Curated icon map for guide sections (keeps the client bundle small). */
export const ICON_MAP: Record<string, LucideIcon> = {
  Hand,
  LogIn,
  MapPin,
  ParkingCircle,
  KeyRound,
  Wifi,
  Thermometer,
  Droplets,
  CookingPot,
  Utensils,
  WashingMachine,
  Tv,
  Trash2,
  Bike,
  ScrollText,
  Moon,
  ShieldAlert,
  LogOut,
  Sparkles,
  TrainFront,
  Car,
  ShoppingCart,
  UtensilsCrossed,
  Pill,
  Stethoscope,
  HelpCircle,
  FileText,
};

export function getIcon(name: string | null | undefined): LucideIcon {
  return (name && ICON_MAP[name]) || FileText;
}
